---
- name: Add Web Up8 Oracle Java OOS.
  apt_repository: repo='ppa:webupd8team/java' update_cache=yes

- name: Accept Oracle License
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections

- name: Install Oracle 8 Java
  apt: "name={{ item }} state=present"
  with_items:
    - oracle-java8-installer
    - oracle-java8-set-default

- name: Install Build dependencies
  apt: "name={{ item }} state=present"
  with_items:
    - libsqlite3-dev
    - build-essential
    - git
    - git-core
    - sqlite3
    - zlib1g-dev
    - libreadline6
    - libreadline6-dev
    - libc6-dev
    - ncurses-dev
    - automake
    - libtool
    - bison
    - pkg-config
    - libyaml-dev
    - libxml2-dev
    - libxslt-dev
    - autoconf
    - curl
    - imagemagick
    - libcurl4-openssl-dev
    - libxvidcore-dev

- name: Install Clamav
  apt: "name={{ item }} state=present"
  with_items:
    - clamav
    - libclamav-dev
