---
- name: install postgresql 
  apt: "name={{ item }} state=present"
  with_items:
    - postgresql
    - libpq-dev

- name: postgresql | add db user
  postgresql_user: name={{dbuser}} password={{dbpass}}

- name: postgresql | add database
  postgresql_db: name={{dbname}} encoding='UTF-8' template='template0' owner={{dbuser}}

- name: postgresql | configure md5 auth for dbuser
  template: src=templates/pg_hba.conf.j2 dest=/etc/postgresql/9.3/main/pg_hba.conf
  notify: restart postgresql
